---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jwt-mock-provider
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jwt-mock-provider
    spec:
      imagePullSecrets:
      - name: regsecret
      containers:
        - name: jwt-mock-provider
          image: registry.cluster-edge.eapp.fi/theikkila/jwt-mock-auth-provider
          ports:
          - containerPort: 8080
          env:
          -
            name: PRIVATE_KEY
            value: "the-real-key"

---
apiVersion: v1
kind: Service
metadata:
  name: jwt-mock-provider
  labels:
    app: jwt-mock-provider
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: jwt-mock-provider


---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jwt-mock-provider
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/proxy-body-size: 5m
spec:
  tls:
  - hosts:
    - jwt-mock-auth.cluster-edge.eapp.fi
    secretName: jwt-mock-auth-tls
  rules:
  - host: jwt-mock-auth.cluster-edge.eapp.fi
    http:
      paths:
      - backend:
          serviceName: jwt-mock-provider
          servicePort: 8080
